apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-random
  labels:
    app: nginx-random
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-random
  template:
    metadata:
      labels:
        app: nginx-random
    spec:
      initContainers:
      - name: echo
        image: busybox
        command: ["/bin/sh", "-c", 'echo "<h1>I am $RANDOM </h1>" > /data/index.html']
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
        - name: conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: data
        emptyDir: {}
      - name: conf
        configMap:
          name: nginx-conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-random
  annotations:
    # traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  selector:
    app: nginx-random
  ports:
    - protocol: TCP
      port: 80
